/*
* @file Dosya adı:BLM202_Proje2_OmerKucuker.jar
* @description Öncelikli Kuyruk Yapısının Kullanıldığı Java Swing uygulaması. 
* @assignment 2.Proje Ödevi
* @date 24.12.2019
* @author Ömer Faruk KÜÇÜKER - omerfaruk.kucuker@stu.fsm.edu.tr
 */
package QueueJframe;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author küçüker
 */
public class priorityQueue extends javax.swing.JFrame {

    Queue kuyruk = new Queue();
    Queue kuyruk2 = new Queue();

    DefaultListModel list1 = new DefaultListModel();
    DefaultListModel list2 = new DefaultListModel();
    DefaultListModel list3 = new DefaultListModel();

    int toplamSure = 0;
    double toplamFatura = 0;

    /**
     * Creates new form priorityQueue
     */
    public priorityQueue() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_readFile = new javax.swing.JButton();
        btn_callCustomer = new javax.swing.JButton();
        btn_toplamSure = new javax.swing.JButton();
        btn_oncelikGir = new javax.swing.JButton();
        btn_oncelikToplam = new javax.swing.JButton();
        btn_toplamFatura = new javax.swing.JButton();
        btn_faturaTur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst1_read = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst2_call = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst3_result = new javax.swing.JList<>();
        txt_sira = new javax.swing.JTextField();
        txt_sure = new javax.swing.JTextField();
        txt_tur = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PriorityQueue");
        setName(""); // NOI18N

        btn_readFile.setText("Dosya Oku");
        btn_readFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readFileActionPerformed(evt);
            }
        });

        btn_callCustomer.setText("Musteri Cagir");
        btn_callCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_callCustomerActionPerformed(evt);
            }
        });

        btn_toplamSure.setText("Toplam Sure");
        btn_toplamSure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamSureActionPerformed(evt);
            }
        });

        btn_oncelikGir.setText("Oncelik Gir");
        btn_oncelikGir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oncelikGirActionPerformed(evt);
            }
        });

        btn_oncelikToplam.setText("Oncelik Toplam Sure");
        btn_oncelikToplam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oncelikToplamActionPerformed(evt);
            }
        });

        btn_toplamFatura.setText("Toplam Fatura");
        btn_toplamFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamFaturaActionPerformed(evt);
            }
        });

        btn_faturaTur.setText("Fatura Gir");
        btn_faturaTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faturaTurActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lst1_read);

        jScrollPane2.setViewportView(lst2_call);

        jScrollPane3.setViewportView(lst3_result);

        jLabel1.setText("Musteriler Listesi");

        jLabel2.setText("Kuyruktan Cikan Musteriler");

        jLabel3.setText("Sonuc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_readFile)
                    .addComponent(btn_callCustomer)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_toplamSure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_oncelikGir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_oncelikToplam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_faturaTur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_toplamFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sira)
                            .addComponent(txt_sure)
                            .addComponent(txt_tur, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_readFile)
                    .addComponent(btn_toplamSure)
                    .addComponent(btn_toplamFatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_oncelikGir)
                            .addComponent(txt_sira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_oncelikToplam)
                            .addComponent(txt_sure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_faturaTur)
                            .addComponent(txt_tur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_callCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_faturaTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faturaTurActionPerformed

        lst3_result.setModel(list3);
        list3.clear();

        String sira = txt_tur.getText();
        boolean bulundu = false;
        Node temp = kuyruk2.front;
        while (temp != null) {
            if (temp.FaturaTipi.equals(sira)) {
                bulundu = true;
                list3.addElement(temp.toString());
            }
            temp = temp.nextNode;
        }
        if (!bulundu) {
            JOptionPane.showMessageDialog(rootPane, "Fatura Turu Bulunamadı, Büyük Harfe Dikkat Edin");
        }


    }//GEN-LAST:event_btn_faturaTurActionPerformed

    private void btn_readFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readFileActionPerformed
        // TODO add your handling code here:
        JFileChooser txtsec = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = txtsec.showSaveDialog(null);
        lst1_read.setModel(list1);
        if (r == JFileChooser.APPROVE_OPTION) {
            String fileWay = txtsec.getSelectedFile().getAbsolutePath();

            if (fileWay.endsWith(".txt")) {
                File file = new File(fileWay);

                try {

                    Scanner scan = new Scanner(file);
                    while (scan.hasNextLine()) {

                        String line = scan.nextLine();
                        String ad = line.split("#")[0];
                        String fatura = line.split("#")[1];
                        double tutar = Double.valueOf(line.split("#")[2]);
                        int oncelik = Integer.parseInt(line.split("#")[3]);
                        int zaman = Integer.parseInt(line.split("#")[4]);
                        kuyruk.enqueue(ad, fatura, tutar, oncelik, zaman);
                        list1.addElement(kuyruk.rear.toString());
                        /*toplamSure += zaman;
                        toplamFatura += tutar;*/
                    }

                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Dosya Bulunamadı!");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "TXT uzantılı dosya giriniz!");

            }
        }

    }//GEN-LAST:event_btn_readFileActionPerformed

    private void btn_callCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_callCustomerActionPerformed
        // TODO add your handling code here:
        lst2_call.setModel(list2);
        try {
            boolean olduMu;
            do {
                Node current = kuyruk.front;
                Node previous = null;
                Node next = kuyruk.front.nextNode;
                olduMu = false;
                while (next != null) {

                    if (current.oncelik > next.oncelik) {
                        olduMu = true;
                        if (previous != null) {
                            Node temp = next.nextNode;
                            previous.nextNode = next;
                            next.nextNode = current;
                            current.nextNode = temp;
                        } else {
                            Node temp = next.nextNode;
                            kuyruk.front = next;
                            next.nextNode = current;
                            current.nextNode = temp;
                        }
                        previous = next;
                        next = current.nextNode;
                    } else {
                        previous = current;
                        current = next;
                        next = next.nextNode;
                    }
                }
            } while (olduMu);
            kuyruk2.enqueue(kuyruk.front.AdSoyad, kuyruk.front.FaturaTipi, kuyruk.front.FaturaMiktari, kuyruk.front.oncelik, kuyruk.front.zaman);
            toplamSure += kuyruk.front.zaman;
            toplamFatura += kuyruk.front.FaturaMiktari;
            list2.addElement(kuyruk.dequeue().toString());
            list1.removeElement(kuyruk2.front.toString());
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Kuyrukta Eleman Yok");

        }

        /*Node temp = kuyruk.front;
        while (temp.nextNode != null) {
            list2.addElement(temp.toString());
            temp = temp.nextNode;
        }*/
    }//GEN-LAST:event_btn_callCustomerActionPerformed

    private void btn_toplamSureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamSureActionPerformed
        // TODO add your handling code here:
        lst3_result.setModel(list3);
        list3.clear();

        String result = "Toplam sure= " + toplamSure;
        list3.addElement(result);
    }//GEN-LAST:event_btn_toplamSureActionPerformed

    private void btn_toplamFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamFaturaActionPerformed
        // TODO add your handling code here:
        lst3_result.setModel(list3);
        list3.clear();

        String result = "Toplam tutar= " + toplamFatura;
        list3.addElement(result);
    }//GEN-LAST:event_btn_toplamFaturaActionPerformed

    private void btn_oncelikGirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oncelikGirActionPerformed
        // TODO add your handling code here:
        lst3_result.setModel(list3);
        list3.clear();
        try {
            int sira = Integer.parseInt(txt_sira.getText());
            int kac = 0;
            if (sira <= 5 && sira >= 1) {
                Node temp = kuyruk2.front;
                while (temp != null) {
                    kac++;
                    if (sira == temp.oncelik) {
                        String result = temp.AdSoyad + " siraniz=  " + kac;
                        list3.addElement(result);
                    }
                    temp = temp.nextNode;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "1 ile 5 arasında rakam giriniz.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "1 ile 5 arasında rakam giriniz.");
        }

    }//GEN-LAST:event_btn_oncelikGirActionPerformed

    private void btn_oncelikToplamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oncelikToplamActionPerformed
        // TODO add your handling code here:
        lst3_result.setModel(list3);
        list3.clear();
        try {
            int sira = Integer.parseInt(txt_sure.getText());
            int kac = 0;
            if (sira <= 5 && sira >= 1) {
                Node temp = kuyruk2.front;
                while (temp != null) {

                    if (sira == temp.oncelik) {
                        kac += temp.zaman;
                    }
                    temp = temp.nextNode;
                }
                String sonuc = sira + ". onceliğin toplam suresi= " + kac;
                list3.addElement(sonuc);
            } else {
                JOptionPane.showMessageDialog(rootPane, "1 ile 5 arasında rakam giriniz.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "1 ile 5 arasında rakam giriniz.");
        }
    }//GEN-LAST:event_btn_oncelikToplamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(priorityQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(priorityQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(priorityQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(priorityQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new priorityQueue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_callCustomer;
    private javax.swing.JButton btn_faturaTur;
    private javax.swing.JButton btn_oncelikGir;
    private javax.swing.JButton btn_oncelikToplam;
    private javax.swing.JButton btn_readFile;
    private javax.swing.JButton btn_toplamFatura;
    private javax.swing.JButton btn_toplamSure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst1_read;
    private javax.swing.JList<String> lst2_call;
    private javax.swing.JList<String> lst3_result;
    private javax.swing.JTextField txt_sira;
    private javax.swing.JTextField txt_sure;
    private javax.swing.JTextField txt_tur;
    // End of variables declaration//GEN-END:variables
}
